<?php

namespace common\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%collections}}".
 *
 * @property int $id
 * @property string $name
 * @property int|null $created_by
 * @property int $status
 * @property int|null $updated_by
 * @property int|null $created_at
 * @property int|null $updated_at
 *
 * @property User $createdBy
 * @property Images[] $images
 */
class Collection extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%collections}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class,
            [
                'class'=> BlameableBehavior::class,
                'updatedByAttribute' => true
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['created_by', 'updated_by', 'created_at', 'updated_at'], 'default', 'value' => null],
            [['created_by', 'status', 'updated_by', 'created_at', 'updated_at'], 'integer'],
            [['status'],'default','value'=>1],
            [['name'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'created_by' => 'Created By',
            'status' => 'Status',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * Gets query for [[Images]].
     *
     * @return \yii\db\ActiveQuery|ImagesQuery
     */
    public function getImages()
    {
        return $this->hasMany(Image::className(), ['collection' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return CollectionsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CollectionsQuery(get_called_class());
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
